### ISSUE TITLE
Long table in landscape

### ISSUE THREAD

**Issue by junoslukan** [dan-weiss/apa7-latex-cls-source#14]
Consider [the example](https://tex.stackexchange.com/questions/139030/inclusion-of-a-landscape-multipage-table-in-an-apa6-class-document) of a long table that should be rotated into landscape mode.

```latex
\documentclass[man]{apa7}
\usepackage{longtable}
\usepackage{pdflscape}
\begin{document}
\shorttitle{zz}
\begin{landscape}

\begin{longtable}{ccc} 
\caption{test} \\
\hline
Column1 & Column2 & Column3  \\
\hline
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\ 
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    \hline

\end{longtable} % line 36
\end{landscape}    % line 37

\end{document}
```

This works fine as long as the `longtable` package is loaded explicitly.

When loading is as the class option (which is the recommended way), changing only the first two lines:

```latex
\documentclass[man,longtable]{apa7}
%\usepackage{longtable}
```

I get an error:

> \openout4 = document2.ttt
 (document2.ttt))
Runaway argument?
! File ended while scanning use of \next.

I also tried using the `sidewaystable` environment, but could not get it to work together with the `longtable`.

**Comment by dan-weiss** [comment]
I didn't modify the `longtable` implementation from the `apa6` class when making `apa7` so I don't know much about the issues. Please try the instructions in the documentation first (endfloat.cfg) and let me know if that works. 

If that doesn't work, I can look into making these classes work together.

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/17074591/101807582-45533400-3ae3-11eb-8fa8-fe61c28b125a.png">

**Comment by junoslukan** [comment]
Hi dan-weiss, thank you for looking into this!

I did indeed copy the APA7endfloat.cfg to my working folder and renamed it to endfloat.cfg.

I tested this again and found out that using `longtable` as a class option produces a `.ttt` file that is also mentioned in the error pasted above. This file includes the table in question, including `\begin{longtable}` and `\end{longtable}`, but also `\end{landscape}` and `\end{document}`, with no matching `\begin` statements. I am not sure if that helps you at all, but it seemed suspect to me.

Note that this file is *not* produced when loading the `longtable` package explicitly.

Finally, it occurred to me to try the whole thing out without the `endfloat.cfg` file (that I had there all along) and the document compiled fine even with `\documentclass[man,longtable]{apa7}` as class option. 

I hope this helps you narrow down the problem.

**Comment by dan-weiss** [comment]
@junoslukan I believe I solved your problem: instead of using the `landscape` environment, I used the `sidewaystable` environment and it worked. Here my the modified code (with `end float.cfg` in the folder with the project):

```latex
\documentclass[man,longtable]{apa7}
\begin{document}
\shorttitle{zz}

\begin{sidewaystable}
\begin{longtable}{ccc} 
\caption{test} \\
\hline
Column1 & Column2 & Column3  \\
\hline
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\ 
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    Column1 & Column2 & Column3  \\
    \hline

\end{longtable} % line 36
\end{sidewaystable}

\end{document}
```
