### ISSUE TITLE
Paragraphs not indented in manuscript mode

### ISSUE THREAD

**Issue by altsalt** [dan-weiss/apa7-latex-cls-source#16]
Hello, I am using your template and had to manually `\setlength{\parindent}{0.5in}` to comply with the [apa7 paragraph formatting guidelines](https://apastyle.apa.org/style-grammar-guidelines/paper-format/paragraph-format). I see [this line](https://github.com/dan-weiss/apa7-latex-cls-source/blob/12c4595441f367f40d656a045a5090fc13b8a039/apa7/apa7.dtx#L2740) commented out in the class file, but am not TeX-y enough to verify that un-commenting it wouldn't cause issues elsewhere, or whether it is even the correct instance.

**Comment by dan-weiss** [comment]
@altsalt The paragraphs are indented property in the example document and in documents that I am using. Take a look at `longsample`. 

I suspect you may have another package included that is changing the paragraph indentation. 

If you can send me a minimal example that shows the issue, I can see if there is something that needs to be fixed in the class.

**Comment by altsalt** [comment]
> 
> If you can send me a minimal example that shows the issue, I can see if there is something that needs to be fixed in the class.

Thanks @dan-weiss ! Here is an [editable overleaf project](https://www.overleaf.com/2215529975ccnmbkswfyqw) demonstrating the problem.

**Comment by dan-weiss** [comment]
Thanks for sending that example @altsalt! 

The short answer is that the apa7 class wasn’t made to work with a table of contents as they are not included in the [APA style guide](https://apastyle.apa.org/learn/quick-guide-on-formatting#Tableofcontents). I’m sure that with modifications the `apa7` class could be made to work with a TOC if there were a style spec to follow.

The `\maketitle` command must be immediately after `\begin{document}` and should be followed by the first paragraph without a blank line in between. [apa7 class documentation](http://ctan.math.washington.edu/tex-archive/macros/latex/contrib/apa7/apa7.pdf#page7)

_Note that the APA style guide says that the first section should not have a section heading as the paper title appears at the top of the first text page (and explicitly says that the section title “Introduction” should not be used)._

**Comment by altsalt** [comment]
Thanks for looking into this @dan-weiss !

Ahh, that totally makes sense, I added a couple of items to use while writing, with the intention of taking them out before sending it along and that was one of them.

It appears that you came up with a work around, but I will absolutely keep this in mind (as well as removing the Introduction title...) Thanks again!
