### ISSUE TITLE
Varied spacing between paragraphs

### ISSUE THREAD

**Issue by altsalt** [dan-weiss/apa7-latex-cls-source#17]
I noticed that occasionally the spacing between paragraphs is not consistent. I'm not positive, but think it may have something to do with footnotes. [Editable Overleaf MWE](https://www.overleaf.com/2215529975ccnmbkswfyqw) demonstrates this on page 3, though my document has it across a variety of pages.

**Comment by dan-weiss** [comment]
It appears that the font from `\usepackage{CormorantGaramond}` is causing the variation in paragraph spacing. Do you still see the issue without that package?

**Comment by altsalt** [comment]
Yes, but less so. It appears to expand between paragraph spacing when they ALMOST fit on one page. It may just have been a random occurrence that this was more frequent with that specific font.

**Comment by altsalt** [comment]
Thank you for taking the time to look into these things and for the package in general! I'm trying to avoid opening issues which can be readily resolved myself but will be more mindful to comment out other packages.

**Comment by dan-weiss** [comment]
@altsalt Happy to help 👍 . Let me know if you see any other issues. 

I also suggest starting with the `longsample.tex` example file to see what added package may be causing an issue.
