### ISSUE TITLE
How do we write up results in this package

### ISSUE THREAD

**Issue by meesew** [dan-weiss/apa7-latex-cls-source#19]
Maybe there is a good answer somewhere, I am tring to write something like (F[1,6] = 34, etc etc) in the paragraph, do you know how we are supposed to do that with this package? There is an error that says math mode must be enabled?

**Comment by dan-weiss** [comment]
Hi @meesew, 

It is working for me to wrap the in paragraph formulas in '$' (e.g. `$F[1,6] = 34$`). Does that work for you?
