### ISSUE TITLE
Avoid unnecessary biblatex options

### ISSUE THREAD

**Issue by moewew** [dan-weiss/apa7-latex-cls-source#23]
Currently the `apa7` manual recommends loading and loads `biblatex` as follows

https://github.com/dan-weiss/apa7-latex-cls-source/blob/f269eaf595f00e18488f9e78673f9ddc4f6aa125/apa7/apa7.dtx#L791-L794

https://github.com/dan-weiss/apa7-latex-cls-source/blob/f269eaf595f00e18488f9e78673f9ddc4f6aa125/apa7/apa7.dtx#L1238

With a current version of `biblatex-apa` (which is assumed because we want 7th edition APA style) `sortcites=true,` is redundant, because it is implied by `style=apa` (cf. [`apa.bbx`](https://github.com/plk/biblatex-apa/blob/bf51fec289130300483847b8583d1a09cbed6fce/tex/latex/biblatex-apa/bbx/apa.bbx#L328)). 

Furthermore, `sorting=nyt,` might actually be counter-productive since it forces the standard author-year sorting and not the APA sorting defined by `biblatex-apa` as [`apa`](https://github.com/plk/biblatex-apa/blob/bf51fec289130300483847b8583d1a09cbed6fce/tex/latex/biblatex-apa/bbx/apa.bbx#L244-L283) (loaded in [`apa.bbx`](https://github.com/plk/biblatex-apa/blob/bf51fec289130300483847b8583d1a09cbed6fce/tex/latex/biblatex-apa/bbx/apa.bbx#L329)).

So I recommend loading `biblatex` simply as

```latex
\RequirePackage[style=apa, backend=biber]{biblatex}
```

---

`\DeclareLanguageMapping` has not been necessary in `biblatex-apa` since v7.5 came out in November 2017. For new documents I would not recommend adding those lines. Since you are working under the assumption that `biblatex-apa` produces 7th-edition APA style (so is at least at version v9.0 from November 2019), I think it makes sense to stop mentioning `\DeclareLanguageMapping` altogether in the documentation.

**Comment by dan-weiss** [comment]
@moewew Thanks for the suggestion. I like deleting code :)

**Comment by moewew** [comment]
Thank you very much! The `biblatex` examples look much less daunting now.
