### ISSUE TITLE
Online Forums

### ISSUE THREAD

**Issue by zachtheriah** [dan-weiss/apa7-latex-cls-source#30]
[This has been updated]

Hello,

I've been grappling with writing an online forum reference and have not been able to get the bibliography to print properly, specifically the howpublished entry on a misc entry. Here is a MWE:

```latex
\documentclass[12pt]{article}

\RequirePackage[american]{babel}
\RequirePackage[style=apa]{biblatex}

\addbibresource{untitled-1.bib}

\begin{document}
	Document text...

	\nocite{*}
	
	\printbibliography
\end{document}
```

Here is the bibliography file, untitled-1.bib

```latex
@misc{test,
	year={2021},
	author={Author Author},
	title={This is a title},
	note={Tweet},
	url={https://twitter.com},
	howpublished={Social Media}
}
```

Here is the output

![image](https://user-images.githubusercontent.com/6132704/121098998-458f6c00-c7b4-11eb-9126-8fd404e068b9.png)

Here is a reference to the relevant style guide page for APA 7th for the style I am trying to recreate: https://apastyle.apa.org/style-grammar-guidelines/references/examples/online-forum-references. Any help on this issue would be great. Thanks!

**Comment by dan-weiss** [comment]
@zachtheriah This is actually handled by the `biblatex-apa` package but I can point you in the right direction.

The `biblatex-apa` package implements the examples in the APA style guide. One of their tweet examples looks like this:

```latex
% (APA 10.15 Example 103)
% ENTRYTYPE is not a localisation string for such, unfortunately, universal neologisms
@ONLINE{10.15:103a,
  ENTRYSUBTYPE            = {Tweet},
  GROUPAUTHOR             = {{APA Education}},
  GROUPAUTHOR+an:username = {1="@APAEducation"},
  TITLE                   = {College Students are Forming Mental-Health
                             Clubs--and They're Making a Difference @washingtonpost},
  TITLEADDON              = {Thumbnail with link attached},
  EPRINT                  = {Twitter},
  DATE                    = {2018-06-29},
  URL                     = {https://twitter.com/apaeducation/status/1012810490530140161}
}
```

And produces a references like this:

<img width="591" alt="image" src="https://user-images.githubusercontent.com/17074591/121277986-be1f2700-c89f-11eb-9e15-ab088fed9682.png">

You can see all of the APA style guide examples in their [documentation](https://ctan.math.illinois.edu/macros/latex/contrib/biblatex-contrib/biblatex-apa/biblatex-apa-test.pdf). You can then cross-reference that to the included `biblatex-apa-test-references.bib` file.

Hope this helps :).

**Comment by zachtheriah** [comment]
Thank you!
