### ISSUE TITLE
Citation problem

### ISSUE THREAD

**Issue by gabrielino** [dan-weiss/apa7-latex-cls-source#31]
Hello Dan, 
I am sorry to bother you, but I am not able to find a solution.
First of all, thank you for your apa7 latex template.
I am writing because I would like to have a citation in the following way (BLABLA, Harley & Davidson 2000). In APA-7, the citations that are inside parentheses should have the ampersand between the two authors. I tried with \citeauthor, but the citation is printed in the following way, Harley and Davidson. 
I hope I have been clear.

I look forward to hearing from you soon.
Gabriele

**Comment by dan-weiss** [comment]
Citations and references are handled by the [biblatex-apa](https://ctan.org/pkg/biblatex-apa) package. You can review their documentation and feel free to report any issues on their [GitHub issues page](https://github.com/plk/biblatex-apa/issues).

Daniel
