### ISSUE TITLE
Compilation fails because there is no config directory

### ISSUE THREAD

**Issue by fredcallaway** [dan-weiss/apa7-latex-cls-source#35]
I downloaded from CTAN, unzipped, and ran `latex apa7.ins`. It then complains "I can't write on file `././config/APA7american.txt'." This is fixed by adding an empty config directory. Perhaps this directory should be included in the release?

**Comment by dan-weiss** [comment]
CTAN has very strict rules about what is in their zip file. It isn’t possible per their rules to include empty directories.

**Comment by fredcallaway** [comment]
The apa6 release includes the directory along without all the language specific config files. At the very least can we add a line to the readme?

**Comment by dan-weiss** [comment]
CTAN has gotten much stricter as I was developing this package based on `apa6`. 

In terms of the readme, I honestly haven't done a 'real' installation of the package (I have built it in place for development and use the one installed by TeXLive day to day). Could you propose language for the readme? I can then make the change and that will help out future users.

**Comment by fredcallaway** [comment]
Sure thing!  I  think it would actually be better to just add a note to the README telling users to look at the documentation in apa7.pdf. Then, I would add a subsection at the top of usage, labeled Installation (or maybe a separate top-level section) saying the following.
```
To use this package, you must first compile a .cls file. To do this, take the following steps:
\begin{enumerate}
\item Create the config directory, e.g. \texttt{mkdir config}.
\item Run \texttt{latex apa7.ins}. This will create a file apa7.cls.
\item Move/copy apa7.cls to the directory containing your latex project.
\end{enumerate}
```

**Comment by fredcallaway** [comment]
Much thanks!
