### ISSUE TITLE
Colored frames around hyperlinks

### ISSUE THREAD

**Issue by pehkawn** [dan-weiss/apa7-latex-cls-source#37]
Thanks for providing this package!
I noticed the hyperlinks in the text have coloured frames around them.
After compiling the PDF i get red frames around table, turquoise frames around web links, and green links around citations.
This isn't very aesthetically pleasing, and probably not APA7 compliant.
I tried removing the colored boxes by adding the line `\usepackage[hidelinks]{hyperref}` in the document, but I only get the error message "Option clash for package hyperref.".
Any suggestions how to remove it? Anyway, it would probably be better if the frames where invisible by default.

[Edit:]
I just realized I can set `hidelinks` as a class option to remove frames. I can't see this is a class option in the documentation, so I presume this is option is passed on to the article class. However, I still think it would be better if invisible frames were the default option.

**Comment by dan-weiss** [comment]
The `\hypersetup` command can be used to change settings in the `hyperref` package after it is loaded. See the [hyperref manual](https://mirrors.concertpass.com/tex-archive/macros/latex/contrib/hyperref/doc/hyperref-doc.html#x1-40003).
