### ISSUE TITLE
flushend.sty was updated

### ISSUE THREAD

**Issue by henlein** [dan-weiss/apa7-latex-cls-source#38]
In the newest flushend.sty the option "keeplastbox" was removed.
https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/sttools/flushend.sty?revision=60736&view=markup

Therefore apa7 currently does not work.
https://github.com/dan-weiss/apa7-latex-cls-source/blob/d1003b238d3f52cb7d85ce6bc191a46db52d0d86/apa7/apa7.dtx#L2795

Workaround for now:
Copy the older flushend.sty in your project folder
https://tug.org/svn/texlive/trunk/Master/texmf-dist/tex/latex/sttools/flushend.sty?revision=56774&view=markup

**Comment by dan-weiss** [comment]
Based on documentation, it looks like the flushed package now has a new algorithm and the fact they removed the option implies to me it is no longer necessary. Could you try removing the `keeplastbox` option from the apa7.cls and see how your document compiles?

Let me know if it looks good and I can make the change to apa7.

**Comment by henlein** [comment]
Seems to look good.
I could not notice any changes in the generated pdf.
(Tested with the samples from git)
