### ISSUE TITLE
package titlesec in apa7

### ISSUE THREAD

**Issue by FrancoGiarettaG** [dan-weiss/apa7-latex-cls-source#40]
Hi! I was working with the apa7 template for latex and everything went well until i wanted to include the titlesec package. The package inclusion gives me numerous errors. Is there something you recommend doing?

![errori](https://user-images.githubusercontent.com/95288673/144045960-24d4da74-e7cd-4680-b048-e63baef7f7ca.png)

**Comment by dan-weiss** [comment]
The `apa7` class is built off of the `apa6` and implements its own way to format section headers. If you have the time/skill to implement `titlesec` in this class, I would be happy to review a pull request.
