### ISSUE TITLE
Order of years for parenthetical citations of different articles by same authors

### ISSUE THREAD

**Issue by pablobernabeu** [dan-weiss/apa7-latex-cls-source#42]
Hello,

Thank you for this very helpful package.

I would like to report a minor bug. The years of publication are not ordered chronologically in parenthetical citations showing the same authors. For instance, 

> (Günther et al., 2021, 2018)

instead of 

> (Günther et al., 2018, 2021)

The bug does not seem to be affected by any of the following factors: reference tags used, order of reference tags in the Rmd, order of references in the `.bib` file.

I'm using the following configuration in the papaja manuscript:

```
csl:                apa.csl
documentclass:      apa7
classoption:        man
```

The bug can be reproduced using, for instance, the following references

- https://onlinelibrary.wiley.com/doi/full/10.1111/cogs.12549
- https://link.springer.com/article/10.1007%2Fs00426-021-01620-4

Thank you very much for your attention

**Comment by dan-weiss** [comment]
The citations and references are not handled by the `apa7` class but rather the `biblatex-apa` class. When I use the `\parencite{}` command with these two references, I get 
> (Gunther et al., 2018; Gunther et al., 2021)

I'm not sure why it doesn't collapse them together (I did a test, and it will if the whole author list is the same). You can reach out to the authors of the `biblatex-apa` class and see if they can help.

**Comment by pablobernabeu** [comment]
Thanks a lot for all the information

**Comment by pablobernabeu** [comment]
Hi @dan-weiss, 

A patch has now been created in biblatex-apa.
