### ISSUE TITLE
APA 7th style is not correct when citing three or more authors

### ISSUE THREAD

**Issue by pat-githubber** [dan-weiss/apa7-latex-cls-source#44]
Unfortunately, the package **does not behave correctly** according to the official APA 7th style (7th Edition) when it comes to in-text citation of three or more authors for the first citation in the text. Having a reference with three authors, the packages display all three authors in the first in-text citation, which is correct with respect to APA 6th but **NOT** to APA 7th.

According to the [APA website about "Number of authors to include in in-text citations"](https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/author-date), it is clearly stated for APA 7th style:

> For a work with three or more authors, include the name of only the first author plus “et al.” in every citation (even the first citation).

The Package documentation [Package documentation](http://mirrors.ctan.org/macros/latex/contrib/apa7/apa7.pdf) of [this packages](https://www.ctan.org/pkg/apa7) even states the wrong definition:

> A three-author paper \parencite[e.g.,][]{Lassen2006} lists all three authors for the first citation, then only the first author on all subsequent citations \parencite{Lassen2006}

The current literature also refers to the correct APA 7th style with **always** one author in in-text citation when three or more authors are present:

> If the in-text citation (see Chapter 8) involves three or more authors, then the citation is reduced. Specifically, only the first author’s name followed by et al. is used. In the sixth edition, the correct in-text citation was Bradley, Jones, Noble, and Wilson (2019). The correct in-text citation listed for the seventh edition is Bradley et al. (2019).
 
Bradley, L., Noble, N., & Hendricks, B. (2020). The APA Publication Manual: Changes in the Seventh Edition. The Family Journal, 28(2), 126–130. https://doi.org/10.1177/1066480720911625

> If a material has three or more authors, only the first name should be included in the in-text citation, followed by “et al.” For example, the book you are currently reading should be cited as “Iida et al. (2020).”

Iida, Paul, et al. The Concise APA Handbook : APA 7th Edition, Information Age Publishing, Incorporated, 2021. ProQuest Ebook Central, https://ebookcentral.proquest.com/lib/asb/detail.action?docID=6351995.
Created from asb on 2022-02-01 11:46:57.

Please, can this vital flaw be corrected.

Despite that, I love the package!!

**Comment by pat-githubber** [comment]
I am sorry, I had an update problem with the package. Now, it works perfectly according to APA 7th

**Comment by dan-weiss** [comment]
@pat-githubber Glad you were able to resolve the issue. FYI, the citations and references are handled by the `biblatex-apa` package and not the `apa7` package. They way that they have versioned the package, as you have discovered, is that same package used to handle APA 6th edition style (now handled by `biblatex-apa6`).

**Comment by pat-githubber** [comment]
Thank you, @dan-weiss !
