### ISSUE TITLE
APA7 crossref

### ISSUE THREAD

**Issue by mvvmvv** [dan-weiss/apa7-latex-cls-source#50]
I am creating my bibliography as follows:
```
@INCOLLECTION{X-a,
    author = {author, another},
    title = {another title},
    pages = {12--34},
    crossref = {X},
}

@BOOK{X,
    author = {author},
    editor = {author},
    title = {title},
    booktitle = {booktitle},
    publisher = {publisher},
    address = {place},
    year = {1234},
}
```
When I create the references it only shows the editors for `X-a` defined in `X`, is this correct?

**Comment by dan-weiss** [comment]
APA style bibliographies are handled by the bib `latex-apa` package. You can file an issue on their [GitHub page](https://github.com/plk/biblatex-apa).
