### ISSUE TITLE
Could you share the samples source code?

### ISSUE THREAD

**Issue by ekiim** [dan-weiss/apa7-latex-cls-source#59]
I'm wondering if you can share the `.tex` file that produces the `.pdf` files you show in the samples.

**Comment by avidseeker** [comment]
Have you taken a look in the documentation? Check page 15.

```sh
texdoc apa7
```

**Comment by quark67** [comment]
It's only for shortsample, not for longsample. So the "closed as completed" is wrong. Where is the code for longsample.pdf?
