### ISSUE TITLE
Title after Abstract

### ISSUE THREAD

**Issue by berentelg** [dan-weiss/apa7-latex-cls-source#8]
Hello,

i do not know, if this is the right place to ask my question (if not, I can delete this post):
I would like to disable the printing of the title after the abstract page. Before the first section starts, the title is printed. It is not necessary for my needs.

Is there any way to disable the title printing after the abstract?

The "\maketitle" function does not change anything related to the title after the abstract.

Best wishes,
Max Berentelg

**Comment by dan-weiss** [comment]
You can add the `donotrepeattitle` option in your documentclass and that should do the trick. Looks like that option was left out of the manual, I will fix that.
